### ISSUE TITLE
压缩文件夹报错

### ISSUE THREAD

**Issue by 183181731** [zwStar/amd-zip#1]
var zip = new AdmZip();
zip.addLocalFolder(dic);
zip.writeZip(zip);

压缩文件夹时报错，提示
TypeError: entry.rawEntryName.copy is not a function
    at d:\WebstormProjects\testgitnode\node_modules\@zwg\adm-zip\zipFile.js:273:24
    at Array.forEach (<anonymous>)
    at Object.compressToBuffer (d:\WebstormProjects\testgitnode\node_modules\@zwg\adm-zip\zipFile.js:264:14)
    at Object.writeZip (d:\WebstormProjects\testgitnode\node_modules\@zwg\adm-zip\adm-zip.js:623:23)
    at Object.<anonymous> (d:\WebstormProjects\testgitnode\ttt.js:79:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by 183181731** [comment]
这个问题更改了zipEntry.js中的
get rawEntryName()方法的返回
return Buffer(iconv.decode(_entryName, encode));  解决了
不过中文的文件或者文件夹打包成zip，依然会乱码。
